# Test your FastAPI endpoints

GET http://127.0.0.1:8053/
Accept: application/json

###

GET http://127.0.0.1:8053/hello/User
Accept: application/json

###

POST http://127.0.0.1:8053/inference
Accept: application/json
Content-Type: application/json

{
  "item": "cambio de fuente de letra en CSS"
}

###

POST http://127.0.0.1:8000/inference
Accept: application/json
Content-Type: application/json

{
  "item": "template html"
}


